### ISSUE TITLE
use l10n.js for interpolate

### ISSUE THREAD

**Issue by Timmaks** [mozillahispano/openwapp#103]
@duesenfranz , i can find any contacts of you so i do it this way.

I work on porting the l10n system of openwapp to l10n.js and have a small problem in login.js where you worked on

<code>
message = interpolate(l10n[stringId], {
            country: this.countryTables.getCountryByMccMnc(
              this.selectedSimCard.mcc, this.selectedSimCard.mnc)
            });
</code>

can be changed to 
<code>
 message = navigator.mozL10n.get([stringId], {
            'country': countryName
          });
</code>

where 'countryName' is a var filled with countryname of the detected country. But doing 

<code>
	  countryName = this.countryTables.getCountryByMccMnc(this.selectedSimCard.mcc, this.selectedSimCard.mnc);
</code>  
result in a empty var in the version without interpolate, what do i miss?

Thanks

**Comment by duesenfranz** [comment]
Sorry for the delay... :sunny:

Anyhow, there were quite a few bugs in there, they are fixed [here](https://github.com/duesenfranz/openwapp/commit/6ca8d3081c909a62b1bd7c98b24e56429e68eb2a) :)

``getCountryByMccMnc`` actually gave back an object, and it's name was under ``.attributes.name``.

I guess I didn't even see this bug because the l10n code replaced the ``{{country}}`` expression by the existing (useless?) translation for ``country``, before the interpolation even started.

However, the last version works for me; sorry for the inconvenience :sunny:

**Comment by duesenfranz** [comment]
We also might want to change the country names in countries.js with the localized country names, or add a new field....

**Comment by Timmaks** [comment]
Yes we need something else so we can localize the country names. I gues something excised  allready inside gaia. Can you work on it @duesenfranz ?
