### ISSUE TITLE
White screen when executing current version (own build)

### ISSUE THREAD

**Issue by naitsirch** [mozillahispano/openwapp#129]
Hi.
I have setup my dev environment and tried to build the latest version (git commit f197065a605072664f46e047d47a5e0b3538b12f). When starting the app on my device with the Firefox WebIDE, I only get a white screen.

So I have checked out commit bbe70162c308e31df8f334edd9b73f7b5d4dede8 again and that worked. So it seems like there are recent changes which breaks the app at least on my device, Firefox OS 1.3 on ZTE Open C.

Any ideas what the reason could be, or how to solve this issue?

**Update**: After further testing, I realized, that this issue occurs again after the first change in the code, running `grunt` and starting the app in the WebIDE again.

**Comment by Timmaks** [comment]
Have you done the steps for troubleshouting (ie because of change of the coseme version you have to run bower again): 

If after updating the code the tests or jshint are failing, maybe you have outdated dependencies. First thing to do is to update all the dependencies:

$ npm install
$ bundle install
$ bower install

Sometimes npm install does weird things, if you keep receiving errors when executing it, just remove the node_modules folder inside the repo and execute npm install again.

To check that all the dependencies are correctly installed, do a npm list and check that no errors appear.

**Comment by naitsirch** [comment]
I have done a fresh `npm install` and `bower install` ;-)
But I don't know what `bundle install` was for. It didn't work for me, because I had to enter a password that I did not know. I have never done anything with ruby or ruby-gems before... maybe you could clarify this for me?

**Comment by naitsirch** [comment]
@Timmaks the problem is, that the *Promise* class is not available in Firefox OS 1.3 (plattform version 28.0). As I am trying to create a bugfix, what do you think about using https://github.com/petkaantonov/bluebird as a fallback for FOS versions that have not enabled the *Promise* class?

And do you know if there's a clean way to include the fallback library only if *Promise* is not avaiable natively?

**Comment by Timmaks** [comment]
Can you first test to update the l10n script to the latest version from https://raw.githubusercontent.com/mozilla-b2g/gaia/master/shared/js/l10n.js 

otherwise we can revert the update of the script to the previous version

**Comment by Timmaks** [comment]
just to make sure, can you build your own version of the 1.7.x branch?

**Comment by willyaranda** [comment]
Hey,

I would use a 1.3+ valid l10n.js

https://github.com/mozilla-b2g/gaia/tree/v1.3/shared/js

**Comment by Timmaks** [comment]
@willyaranda yeah i think that is also better, and i don't think we use any new function of the master branch

**Comment by naitsirch** [comment]
Thanks for your hints! I have checked out openwapp 1.7.x branch and built it, which worked well ;-)
I have tried to use the l10n.js from Gaia v1.3, but that did also fail. No texts were shown and there wer many console logs, saying that translation codes are missing. It looked like the resources have not been loaded.

Well I think I'll try to develop against 1.7.x branch. I think you can close this issue. But maybe you can add the notice to the README.md, that the 1.7.x branch should be used for Firefox OS 1.3

Thanks!

**Comment by Timmaks** [comment]
Thanks for bringing this up. i have to amid i didn't use 1.3 for testing the new l10n system. I am going to revert the l10n.js script back to the version of 1.3. because we need the new l10n also in the 1.7.x branch.
 
That you fail is right, the way how the script connects to the translation files is changed between the two scrips.
going to work on this and will ask you to test again when i am finished

**Comment by Timmaks** [comment]
@naitsirch i just updated the l10n system on the master, can you please build your version from themaster and confirm that is fixed for your phone ( i tested it on a keon with version 1.3)

**Comment by naitsirch** [comment]
@Timmaks yes, *master* works fine, now. Confirmed ;-)
