### ISSUE TITLE
registration error

### ISSUE THREAD

**Issue by mduemke** [mozillahispano/openwapp#204]
Hello there,

I installed the newest version 1.9.5 on Firefox 2.0

but on registration there is the message that an upgrade is needed
and the registration process fails.

**Comment by chocoelho** [comment]
Same here, but on Firefox 2.6.

**Comment by Timmaks** [comment]
suddenly i had the same error,  any change on a fix @willyaranda

**Comment by Birnd** [comment]
App doesnt work anymore, when started the Registration Screen pops up even though ive been using it already.

**Comment by aticat** [comment]
What are the plans for solving this problem?

**Comment by willyaranda** [comment]
Work should be done in https://github.com/mozillahispano/coseme, not here.

**Comment by willyaranda** [comment]
Keeping this open to keep the track here, so people don't drive mad.

**Comment by Keleitse** [comment]
Have been some days now without accessing openwapp, old version pops up

**Comment by Vincent57200** [comment]
Same problem 'old version' 
i made no change. Ffos v. 1.3
please solve the problem.

**Comment by Timmaks** [comment]
@willyaranda how is it going?

**Comment by djoerd** [comment]
Hi @willyaranda, we love openwapp and firefox os, any chance that the app will be up again?

**Comment by Omega246** [comment]
I hope its not rude or annoying, but may i ask for some information regarding the update?

Is it dead? Or is it just more labourintensive this time?

I ask, because i love this programm and if i can help you(with no programming-skills) in any way, just ask.

Thank you very much.

**Comment by aticat** [comment]
Sorry, I can't say anything about this subjet because I was only a sad 
user of openwapp.
Since nearly one month it didn't work anymore on by both Firefox Alcatel 
E and there is no new version at the Marketplace.
What a pity!

Am 13.04.2016 um 16:57 schrieb Omega246:

**Comment by aticat** [comment]
Sorry, I can't say anything about this subjet because I was only a sad user  of openwapp. 
 Since nearly one month it didn't work anymore on by both Firefox Alcatel E and there is no new version  at the Marketplace.
 What a pity!
 
-----Ursprüngliche Nachricht-----
 Von: "Omega246" [notifications@github.com]
 Gesendet: Mi. 13.04.2016 16:57
 An: "mozillahispano/openwapp" [openwapp@noreply.github.com]
 Kopie: "aticat" [chirinegramke@freenet.de]
 Betreff: Re: [mozillahispano/openwapp] registration error (#204)

I hope its not rude or annoying, but may i ask for some information regarding the update?
Is it dead? Or is it just more labourintensive this time?
I ask, because i love this programm and if i can help you(with no programming-skills) in any way, just ask.
Thank you very much.
—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
-----Ursprüngliche Nachricht Ende-----
 

---
Alle Postfächer an einem Ort. Jetzt wechseln und E-Mail-Adresse mitnehmen! Rundum glücklich mit freenetMail

**Comment by willyaranda** [comment]
Openwapp will not have any updates sometime soon. If you need to use Whatsapp on Firefox OS, please search for LoquiIM on the marketplace.

**Comment by aticat** [comment]
THANKS FOR YOUR ANSWER!


Am 19.04.2016 um 12:36 schrieb Guillermo López Leal:
