### ISSUE TITLE
Add meaningful message for too_many error on registration

### ISSUE THREAD

**Issue by Otsche** [mozillahispano/openwapp#47]
2 months ago i downloaded openwapp first time, registered, sms came, everything ok and worked well.
last sunday the problems started, ever when i opened openwapp, i saw 2-3 seconds my friends and groups and then the registration windows pops up. i tried to re-register 1000 times but no success. i ever got the error message that there is a connecting problem. your new version 1.5 also doesnt helped me.

facts:
alcatel one touch fire e
country: germany
sim card is inside
congstar (telekom)

i tried with 2g, 3g and two different wifi´s

**Comment by holztest08** [comment]
Hi,
I have the same problem with my Flame (2.1) and the latest OpenWapp version:
"No cell routes for sending sms caused by your operator. Please try again later or contact OpenWapp developers"
I've tried it with both SIMs, mobile connections and wifi.
When I try to send curl with my phone number I get:
{"status":"fail","reason":"no_routes","retry_after":3600}
Any suggestions?

**Comment by duesenfranz** [comment]
@holztest08 
Unfortunately, thats a bug (#61) which we have yet to solve.
