### ISSUE TITLE
How to add someone to a group?

### ISSUE THREAD

**Issue by feklee** [mozillahispano/openwapp#93]
The admin of a group made me co-admin. *How can I add someone to the group?*

**Comment by willyaranda** [comment]
This is not possible for now. 

On https://github.com/mozillahispano/openwapp/blob/2b3334f7d3ec27339c992b75dcdc6b8e991c2919/app/scripts/models/contact.js#L53-60 we extract the first part of the `jid` send by WA, something like: 1234-5678@g.us

When we started, the 1234 was the only administrator of the group, but that has changed. I have not deep into the protocol about how WA sends the info about the admins, so you cannot edit it since the controls are not shown (because we think that you are not the admin, because of the `jid`)
